yclim/gem

- .gitignore
- README.md
- pom.xml
- src/main/resources/static/index.html
@all First PR to start the motion going... closes #1
> Basic tomcat setup

- .gitignore
- README.md
- app/package.json
- pom.xml
change yarn watch -out-dir to target folder and add spring-boot-dev-tool for live reloading
> #15 Make yarn-watch-live-reloading work

- pom.xml
- src/main/java/innohack/gem/dao/BasicGroupDao.java
- src/main/java/innohack/gem/dao/IGroupDao.java
- src/main/java/innohack/gem/entity/Group.java
- src/main/java/innohack/gem/entity/ParamType.java
- src/main/java/innohack/gem/entity/Parameter.java
- src/main/java/innohack/gem/entity/Rule.java
- src/main/java/innohack/gem/service/GroupService.java
- src/main/java/innohack/gem/web/GroupController.java
- src/main/resources/application.properties
Not wanting to block, so here is the first cut for backend mvc. Rest endpoint is /api/group (example only). 
@yclim The entities I try follow from your mock... only change is I merged up the parameters of the rule and rule instances (defined in your rule and group). Feel free to change the entities.
closes #3 ? (enough for a basic scaffold?)
> 3 rest endpoint

- .gitignore
- README.md
- pom.xml
- src/main/java/innohack/gem/filegen/GenUtil.java
- src/main/java/innohack/gem/filegen/GenerateMockFiles.java
- src/main/java/innohack/gem/filegen/PdfFileGenerator.java
added a mock pdf file generator utility.
close #2 and create new issue to build csv and excel file generator?
> 2 load up mock data

- pom.xml
- src/main/java/innohack/gem/controller/DocumentController.java
- src/main/java/innohack/gem/dao/DocumentDao.java
- src/main/java/innohack/gem/dao/IDocumentDao.java
- src/main/java/innohack/gem/entity/DocumentMetadata.java
- src/main/java/innohack/gem/example/ExtractBasicFileInfo.java
- src/main/java/innohack/gem/service/DocumentService.java
-- basic modal for document metadata (will take reference from tc and shaojie later)
-- added idao, dao and service to get document metadata
-- added example code to extract basic file metadata from multipart file
> 6 basic information from file

- app/package.json
- app/src/App.tsx
- app/src/BrowseFiles.tsx
- app/src/EditGroups.tsx
- app/src/FileList.tsx
- app/src/RuleList.tsx
- app/src/api/index.d.ts
- app/src/index.html
- app/tsconfig.json
- pom.xml
I also added the springboot:run Maven goal to my GemApplication run configuration so that the UI is built and static files copied to the target folder when Tomcat is started.
> 17 static folder not added to jar

- README.md
- src/main/java/innohack/gem/filegen/CsvFileGenerator.java
- src/main/java/innohack/gem/filegen/GenUtil.java
- src/main/java/innohack/gem/filegen/GenerateMockFiles.java
- src/main/java/innohack/gem/filegen/PdfFileGenerator.java
add csv generation utility. closes #22
> 22 csv generator

- pom.xml
- src/main/java/innohack/gem/filegen/CsvFileGenerator.java
- src/main/java/innohack/gem/filegen/ExcelFileGenerator.java
- src/main/java/innohack/gem/filegen/GenerateMockFiles.java
- src/main/java/innohack/gem/filegen/PdfFileGenerator.java
code to generate excel files. closes #23
> 23 excel generator

- app/src/BrowseFiles.tsx
- app/src/api/GEMFileAPIService.js
- src/main/java/innohack/gem/dao/GEMFileDao.java
- src/main/java/innohack/gem/dao/IGEMFileDao.java
- src/main/java/innohack/gem/entity/GEMFile.java
- src/main/java/innohack/gem/entity/gem/data/CsvFeature.java
- src/main/java/innohack/gem/example/tika/TikaTextAndCsvParser.java
- src/main/java/innohack/gem/example/tika/TikaUtil.java
- src/main/java/innohack/gem/extractor/opencsv/OpenCsvParser.java
- src/main/java/innohack/gem/service/GEMFileService.java
- src/main/java/innohack/gem/web/GEMFileController.java
> 37 file extension api

- app/src/App.scss
- app/src/BrowseFiles.tsx
- app/src/api/GEMFileAPIService.js
- src/main/java/innohack/gem/WebConfiguration.java
> 39 yarn watch not working

- pom.xml
- src/main/java/innohack/gem/example/ExtractHtml.java
-added sample code to extract info from html files
> 51 extract features from html

- app/package.json
- app/src/App.tsx
- app/src/EditGroups.tsx
- app/src/FileList.tsx
- app/src/GroupCard.tsx
- app/src/GroupList.tsx
- app/src/RuleList.tsx
- app/src/api/index.d.ts
- pom.xml
> 46 tslint problems

- pom.xml
- src/main/java/innohack/gem/example/RockDBSample.java
sample code to show how rocksdb works
> 8 feature store exploration

- app/src/App.scss
- app/src/BrowseFiles.tsx
> 40 sync spinner

- src/main/java/innohack/gem/filegen/CsvFileGenerator.java
- src/test/java/innohack/gem/GemApplicationTests.java
Using both csvgeneration and gemfile to create a fixed set of csv file for testing purpose to make sure extraction on content and metadata doesnt break
> testing code for csv extraction

- README.md
- src/main/java/innohack/gem/entity/GEMFile.java
- src/main/java/innohack/gem/entity/rule/Parameter.java
- src/main/java/innohack/gem/entity/rule/rules/FileExtension.java
- src/main/java/innohack/gem/util/Util.java
- src/main/resources/logback.xml
- src/test/java/innohack/gem/GemApplicationTests.java
- src/test/java/innohack/gem/entity/rule/rules/FileExtensionTest.java
- src/test/resources/dump.txt
A simple file extension rule with unit tests. Not sure if it's the flow of rules that you groups are thinking of... 
@yclim I commented out the GemApplicationTests as it is failing in master branch. Can you check it out?
Closes #81
> 81 fileext rule

- app/src/App.scss
- app/src/BrowseFiles.tsx
- app/src/EditGroups.tsx
- app/src/FileList.tsx
- app/src/GroupCard.tsx
- app/src/GroupList.tsx
- app/src/RuleList.tsx
- src/main/java/innohack/gem/filegen/CsvFileGenerator.java
- src/test/java/innohack/gem/GemApplicationTests.java
clean up hackish css layout code
close #83
> cleanup css code to use layout primitive (i.e grid, stack, box, flex)

- app/src/EditGroups.tsx
- app/src/GroupCard.tsx
- app/src/GroupList.tsx
- app/src/RuleList.tsx
- app/src/api/FileService.ts
- src/test/java/innohack/gem/entity/feature/CSVFeatureTests.java
> refactor to use useReducer to manage groups state

- app/src/App.scss
- app/src/FileList.tsx
- app/src/GroupList.tsx
- app/src/api/Api.ts
- src/main/java/innohack/gem/GemApplication.java
- src/main/java/innohack/gem/entity/feature/ExcelFeature.java
- src/main/java/innohack/gem/filegen/CsvFileGenerator.java
- src/main/java/innohack/gem/filegen/ExcelFileGenerator.java
- src/test/java/innohack/gem/GemApplicationTests.java
- src/test/java/innohack/gem/entity/feature/CSVFeatureTests.java
- src/test/java/innohack/gem/entity/feature/ExcelFeatureTests.java
- src/test/java/innohack/gem/entity/feature/TikaFeatureTests.java
- src/test/java/innohack/gem/entity/util/FileUtilForTesting.java
also 
- change `localhost:8080/api` to relative - `api` for CD to  work
- fix no group card width
close #105
> 105 vertical scrolling for filelist

- app/src/EditGroups.tsx
1) need to set group name to input.newGroupName before returning the map. This will allow rulelist to list down the correct list of groups
2) fixed ui not showing correctly when deleting group
> 100 update group name

- app/src/api/GroupRuleService.ts
- src/main/java/innohack/gem/dao/GroupDao.java
- src/main/java/innohack/gem/dao/IGroupDao.java
- src/main/java/innohack/gem/entity/rule/Group.java
- src/main/java/innohack/gem/filegen/CsvFileGenerator.java
- src/main/java/innohack/gem/service/GroupService.java
- src/main/java/innohack/gem/web/GroupController.java
- src/test/java/innohack/gem/service/GroupTest.java
- src/test/java/innohack/gem/service/MatchServiceTests.java
> 111 add groupid

- src/main/java/innohack/gem/entity/rule/RuleType.java
- src/main/java/innohack/gem/entity/rule/rules/TikaContentRegex.java
- src/main/java/innohack/gem/filegen/PdfFileGenerator.java
- src/test/java/innohack/gem/entity/rule/rules/TikaContentRegexTest.java
this is for tika content regex rule trying to match pure text for those tika extracted
> 78 tikacontentrule

- src/main/java/innohack/gem/entity/feature/ExcelFeature.java
- src/main/java/innohack/gem/entity/rule/rules/TikaContentRegex.java
- src/main/java/innohack/gem/filegen/PdfFileGenerator.java
- src/test/java/innohack/gem/entity/rule/rules/TikaContentRegexTest.java
ok remove pathwalker inside the testcase
> remove walkpath from testcase

- app/src/BrowseFiles.tsx
- pom.xml
- src/main/java/innohack/gem/GemApplication.java
- src/main/java/innohack/gem/example/ExtractBasicFileInfo.java
- src/main/java/innohack/gem/service/GEMFileService.java
- src/main/java/innohack/gem/service/GroupService.java
- src/main/java/innohack/gem/web/GEMFileController.java
Some clean-ups and auto run the sample file generator during startup. (currently just pass arguments to the main class to run the samples)
Closes #101
> 101 add files to directory

- src/main/java/innohack/gem/entity/rule/rules/ExcelHeaderColumnValue.java
- src/main/java/innohack/gem/service/GroupService.java
1) null pointer rules from matchservice 
private void removeAllAssociatedRuleFromCache(Group group) {
for (HashMap<Rule, Boolean> map : matchedFileRuleTable.values()) {
for (Rule r : group.getRules()) {
map.remove(r);
}
}
2) set empty rules list before calling matcherservice in groupservice
> 121 fix console error

- src/main/java/innohack/gem/entity/rule/rules/ExcelHeaderColumnValue.java
1) Fixed missing Class Constructor
> ExcelHeaderValues Rule and Testcases 80

- app/src/EditGroups.tsx
- app/src/GroupCard.tsx
> Allow remove rule from a group

- app/src/GroupList.tsx
- src/main/java/innohack/gem/entity/rule/Group.java
- src/main/java/innohack/gem/entity/rule/GroupExportMixin.java
- src/main/java/innohack/gem/service/GroupService.java
- src/main/java/innohack/gem/web/GroupController.java
> Allow export the groups as a json file

- app/src/App.scss
- app/src/App.tsx
- app/src/EditGroups.tsx
- app/src/ExportSpec.tsx
- app/src/ExtractData.tsx
- app/src/GroupCard.tsx
- app/src/mockData.tsx
> 133 mockup extractdata

- .travis.yml
- app/src/GroupList.tsx
- app/src/api/GroupRuleService.ts
- src/main/java/innohack/gem/entity/Project.java
- src/main/java/innohack/gem/service/GroupService.java
- src/main/java/innohack/gem/web/GroupController.java
Closes #128. This imports the spec file exported by #127. (Quite a high chance this will go into conflict due to so many live PRs....)
@yclim I just placed in a basic file upload in the UI. Feel free to prettify it.
> Allow upload and import the spec file

- src/main/java/innohack/gem/entity/rule/rules/TikaMetaValue.java
- src/test/java/innohack/gem/entity/rule/rules/TikaMetadataRegexTest.java
this is for tika metadata rule check
> tikametadata rule check

- app/src/EditGroups.tsx
- app/src/GroupCard.tsx
- app/src/RuleForm.tsx
- app/src/RuleList.tsx
> 149 fix edit group

- src/main/java/innohack/gem/GemApplication.java
- src/main/java/innohack/gem/database/RocksDatabase.java
- src/main/java/innohack/gem/entity/feature/AbstractFeature.java
- src/main/java/innohack/gem/entity/feature/CsvFeature.java
- src/main/java/innohack/gem/entity/feature/ExcelFeature.java
- src/main/java/innohack/gem/entity/rule/RuleFactory.java
- src/main/java/innohack/gem/entity/rule/rules/CsvHeaderColumnValue.java
- src/main/java/innohack/gem/entity/rule/rules/FilenameRegex.java
- src/main/java/innohack/gem/example/ExtractHtml.java
- src/main/java/innohack/gem/example/RockDBSample.java
- src/main/java/innohack/gem/example/opencsv/OpenCsvParser.java
- src/main/java/innohack/gem/example/poi/PoiExcelParser.java
- src/main/java/innohack/gem/example/tika/TikaExcelParser.java
- src/main/java/innohack/gem/example/tika/TikaPdfParser.java
- src/main/java/innohack/gem/example/tika/TikaTextAndCsvParser.java
- src/main/java/innohack/gem/example/tika/TikaTextParser.java
- src/main/java/innohack/gem/example/tika/TikaUtil.java
- src/main/java/innohack/gem/service/GEMFileService.java
- src/main/java/innohack/gem/service/GroupService.java
1) Removed unused print line
2) Change print line to debug message
> 140_Remove_Print_line

- src/main/java/innohack/gem/dao/GroupDao.java
- src/main/java/innohack/gem/dao/GroupRockDao.java
- src/main/java/innohack/gem/dao/IGroupDao.java
- src/main/java/innohack/gem/entity/match/MatchFileGroup.java
- src/main/java/innohack/gem/service/GEMFileService.java
- src/main/java/innohack/gem/service/MatchService.java
- src/main/java/innohack/gem/service/SyncFileService.java
- src/main/java/innohack/gem/web/GEMFileController.java
- src/test/java/innohack/gem/service/MatchServiceTests.java
I renamed ExtractFileService to SyncFileService so not to confuse with the match ExtractService
> 162 api files with nomatches

- app/src/App.scss
- app/src/EditGroups.tsx
- app/src/FileList.tsx
- app/src/FileStat.tsx
- app/src/GroupCard.tsx
- app/src/GroupList.tsx
- app/src/api/GroupRuleService.ts
- app/src/api/index.d.ts
> 168 fix vertical scrolling in filelist

- src/main/java/innohack/gem/dao/ExtractDao.java
- src/main/java/innohack/gem/dao/IExtractDao.java
- src/main/java/innohack/gem/entity/extractor/ExtractConfig.java
- src/main/java/innohack/gem/entity/extractor/ExtractedFile.java
- src/main/java/innohack/gem/entity/extractor/ExtractedRecords.java
- src/main/java/innohack/gem/entity/extractor/TimestampColumn.java
- src/main/java/innohack/gem/service/ExtractService.java
- src/main/java/innohack/gem/service/GroupService.java
- src/main/java/innohack/gem/service/extract/AbstractExtractor.java
- src/main/java/innohack/gem/service/extract/CSVExtractor.java
- src/main/java/innohack/gem/service/extract/Extractor.java
- src/main/java/innohack/gem/web/ExtractController.java
- src/test/java/innohack/gem/entity/extractor/TimestampColumnTest.java
- src/test/java/innohack/gem/service/ExtractServiceTest.java
- src/test/java/innohack/gem/service/SkipRockDBConfig.java
- src/test/java/innohack/gem/service/extract/CSVExtractorTest.java
> Add unit tests and allow CSV extraction

- app/package.json
- app/src/ExtractData.tsx
add timezone select options in ExtractData
> add timezone list for ExtractData.tsx

- .gitignore
- app/package-lock.json
- app/src/EditGroups.tsx
- app/src/ExtractData.tsx
- app/src/FileList.tsx
- app/src/GroupList.tsx
- app/src/StoreContext.tsx
- app/src/api/GroupRuleService.ts
- app/src/api/index.d.ts
- app/src/fileStatActions.tsx
- app/src/fileStatReducer.tsx
> Revert "Reformat and fix tsx"

- src/main/java/innohack/gem/entity/feature/ExcelFeature.java
- src/main/java/innohack/gem/service/extract/ExcelExtractor.java
> Open excel in readonly mode

- src/main/java/innohack/gem/entity/match/MatchFileRule.java
- src/main/java/innohack/gem/entity/rule/rules/TikaContentRegex.java
- src/main/java/innohack/gem/service/MatchService.java
- src/main/java/innohack/gem/service/extract/TikaContentExtractor.java
- src/test/java/innohack/gem/entity/rule/rules/TikaContentRegexTest.java
- src/test/java/innohack/gem/service/MatchServiceTests.java
- src/test/java/innohack/gem/service/extract/TikaContentExtractorTest.java
- src/test/java/innohack/gem/web/GEMFileControllerTest.java
> 197 Fix TCR bug

- app/.babelrc
- app/package.json
- app/src/App.tsx
- app/src/ExtractData.tsx
- app/src/StoreContext.tsx
- app/src/api/ExtractConfigService.ts
- app/src/api/index.d.ts
- app/src/extractConfigActions.tsx
- app/src/extractConfigReducer.tsx
- pom.xml
- src/main/java/innohack/gem/service/ExtractService.java
- src/main/java/innohack/gem/service/extract/AbstractExtractor.java
- src/main/java/innohack/gem/service/extract/CSVExtractor.java
- src/main/java/innohack/gem/service/extract/ExcelExtractor.java
- src/main/java/innohack/gem/service/extract/ExtractorFactory.java
- src/main/java/innohack/gem/service/extract/TikaContentExtractor.java
- src/main/java/innohack/gem/web/ExtractController.java
- src/test/java/innohack/gem/service/ExtractServiceTest.java
- src/test/java/innohack/gem/service/extract/ExtractorFactoryTest.java
- src/test/java/innohack/gem/service/extract/TikaContentExtractorTest.java
> 191 link up extractor and timestamp form

- app/src/ExtractData.tsx
- app/src/FileList.tsx
- app/src/api/GroupRuleService.ts
- app/src/api/index.d.ts
- src/main/java/innohack/gem/entity/GEMFile.java
Filter group-tab with matched file in ExtractData
Added Last modified and creation time.
> 203-FileTime

- app/src/ExportSpec.tsx
- app/src/GroupList.tsx
- app/src/api/Api.ts
- app/src/api/GroupRuleService.ts
- app/src/api/index.d.ts
- src/main/java/innohack/gem/service/GroupService.java
- src/main/java/innohack/gem/web/GroupController.java
Load groups from imported spec
Move export specs to ExportSpec.tsx
> 147-import_export_rules

- app/src/ExportSpec.tsx
- app/src/ExtractData.tsx
- app/src/FileDataList.tsx
- app/src/FileList.tsx
- app/src/api/index.d.ts
Quick fix by adding client side table pagination. Still takes a few seconds to display large csv/excel table (~2 sec on 6mb csv file). Could implement server side paging next time to improve performance.
close #202
> 202 handle large file
